name: glm-image
display_name: "GLM Image Generator"
version: 1.9.0
description: >
  Generate images from text prompts using the GLM-Image API (BigModel / Zhipu AI).
  Use when the user wants to generate, create, or draw an image. Triggers on:
  "generate an image of...", "create a picture of...", "draw...", "make an image of..."
attribution:
  source: https://github.com/ViffyGwaanl/glm-image
  author: ViffyGwaanl
  license: MIT
permissions:
  - exec
  - read
triggers:
  - generate an image
  - create a picture
  - draw a
  - make an image
  - generate image of
  - create image of
